### ISSUE TITLE
inRange

### ISSUE THREAD

**Issue by ghost** [daveybfire/codecademy#1]
https://github.com/daveybfire/codecademy/blob/ab28e6e6482d06027c7bb65864c3489d543ce4c3/_.js#L9-L25

This definitely works but could be written more concisely. Keep in mind that if you're returning true or false based on whether some condition holds, you can just return the condition itself and save yourself some lines of code.

```javascript
  inRange: function (number, start, end) {
    if (!end) {
      // Use the start parameter as the "end" of the range.
      return number >= 0 && number < start;
    } else {
      // By default, assume the start value is less than the end value.
      let inRange = number >= start && number < end;
      // If it's not, just flip the assumed boolean value.
      return start < end? inRange : !inRange;
    }
  },
```

**Comment by daveybfire** [comment]
Thanks
