### ISSUE TITLE
words

### ISSUE THREAD

**Issue by ghost** [daveybfire/codecademy#2]
https://github.com/daveybfire/codecademy/blob/ab28e6e6482d06027c7bb65864c3489d543ce4c3/_.js#L27-L28

Try to avoid using global variables, especially if you're using a variable name that exists in the outer scope. Use `let` or `const` in order to bind variables to the current scope.

Alternatively, you can just return the split expression if you're not going to do anything else with its resulting value:

```javascript
words: function (string) { 
  return string.split(' ');
},
```

**Comment by daveybfire** [comment]
I need to work on this - thanks
