### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [daveybfire/codecademy#7]
Satisfactory 👍 

Great job getting all the functions to return the expected output. This was a great exercise in algorithmic thinking and it looks like you've got a good handle on using the language to solve real problems.

That being said, don't forget that even working code can be brittle if you don't follow certain best practices. Using `let/const/var` should be used more throughout your code at the minimum, it's never a good idea for a module with an indefinite number of functions to use the same pool of variables for each function. A comment here and there would definitely be a nice tough also!

**Comment by daveybfire** [comment]
Thanks - good points to take onboard. Thanks for the feedback.
